### ISSUE TITLE
Register Screen (JavaScript)

### ISSUE THREAD

**Issue by mikesz88** [mikesz88/DevSpace_FE#14]
Register Screen (HTML/CSS) must be completed first before working on this issue.

You will be working on the login.html page

Requirements:
- [ ] Create variables for what the inputs give you (email & password)
- [ ] On the Submit button, have it do a fetch/Post request to the API called `/auth/register` with a body of: {email: xxx, password: xxx}
- [ ] Create an error condition if the API call comes back for "Email is already used. Please try again."  (It does not need to be fancy. It can be the alert things if preferred.)
- [ ] If successful, the response is going to provide a token. Please store the token in the local storage as: "token: XXX". This is important as you will need it for authentication purposes on the web app. 
- [ ] If Registration is also successful, please have them go to the registerAndEditPartOne.html (you will need to create this HTML file - it can be blank)

Wireframe: 
![image](https://github.com/mikesz88/DevSpace_FE/assets/88916004/dbd02a09-defc-4e27-8c1c-958eb694045e)

**Comment by mikesz88** [comment]
In the ticket: [Register Screen (HTML/CSS)](https://github.com/mikesz88/DevSpace_FE/issues/12), please wait for a comment in here before working on this ticket. This ticket is blocked until Register HTML/CSS is completed and in Main branch

**Comment by Whitehex** [comment]
ready to be worked
